### ISSUE TITLE
Text in labels is displaced

### ISSUE THREAD

**Issue by ivan-kleshnin** [Paqmind/paqmind#10]
Sits lower than visual center

**Comment by scabbiaza** [comment]
![screen shot 2016-01-20 at 16 48 19](https://cloud.githubusercontent.com/assets/2734464/12452279/4a150c2a-bf96-11e5-9cd9-587cba4b0ef7.png)

what do you think now?

**Comment by ivan-kleshnin** [comment]
It still looks 1px lower than line of the main font.

**Comment by ivan-kleshnin** [comment]
No longer relevant
