### ISSUE TITLE
Improve font for headers

### ISSUE THREAD

**Issue by ivan-kleshnin** [Paqmind/paqmind#2]
I propose to change font to `Volkhov italic` for headers other than H1. 
H5 / H6 may stay PT Sans if they look better that way.
In addition, H3 seems too small for it's space. I'd like to see H3 bigger than now.
I'd like to revisit header font sizes once again.

http://www.smashingmagazine.com/2009/08/typographic-design-survey-best-practices-from-the-best-blogs/

**Comment by scabbiaza** [comment]
I have added styleguides file. Now you can find only headers there: https://github.com/Paqmind/paqmind/pull/3

I have added `Volkhov italic` for `h1, h2, h3, h4`
I have left main font-family for `h5 & h6`, that is `source-sans-pro`.
I don't think h3 is small, all headers sizes look very proportional.
But i updated `margin-bottom`: descreased it for smaller headers.
I also have added classes `.h1, .h2`.

What do you think?

**Comment by ivan-kleshnin** [comment]
1. Headers look better but distances feel wrong enough to me.
2. I want to have vertical rhytm in this site so I ask you to add grid to styleguide that we can inspect how things are going.

**Comment by ivan-kleshnin** [comment]
We need GRID.png.

**Comment by scabbiaza** [comment]
Done in `redesign` branch
