### ISSUE TITLE
Tables should be styled properly

### ISSUE THREAD

**Issue by ivan-kleshnin** [Paqmind/paqmind#22]
http://paqmind.com/posts/clojure-vs-elm/

**Comment by scabbiaza** [comment]
![screen shot 2016-07-02 at 11 28 33](https://cloud.githubusercontent.com/assets/2734464/16539324/2ac71150-4048-11e6-856d-f591d9033935.png)

Added styles in courses branch

**Comment by ivan-kleshnin** [comment]
Can you add HTML (examples) page which won't be showed in menu but will be accessible through `paqmind.com/pages/html`? I feel I'll forget this `very basic table` stuff soon (not they have bad names – just memory is too overloaded).

**Comment by scabbiaza** [comment]
Pls add such page `http://localhost:8080/pages/html`. Missing now

**Comment by ivan-kleshnin** [comment]
`pages/htmltest`

**Comment by scabbiaza** [comment]
Looks ok?
![screen shot 2016-07-19 at 09 00 54](https://cloud.githubusercontent.com/assets/2734464/16940023/65eb2e3e-4d8f-11e6-8bb9-6813b06950a7.png)

**Comment by ivan-kleshnin** [comment]
Good. I've changed all headers to be left-aligned.
