### ISSUE TITLE
Courses page

### ISSUE THREAD

**Issue by scabbiaza** [Paqmind/paqmind#25]
Pls check this comment, don't know why it doesn't work
https://github.com/Paqmind/paqmind/blob/courses/themes/paqmind/templates/page/courses.html#L24

Here is the current look
![screen shot 2016-07-02 at 11 01 06](https://cloud.githubusercontent.com/assets/2734464/16539234/d7f8c416-4045-11e6-8bd5-c4638c5fea10.png)

The row after the course description is not fancy, but it's very readable and i like it.
Or maybe i'm just not in the mood to create anything today.

**Comment by ivan-kleshnin** [comment]
> Pls check this comment, don't know why it doesn't work

Data for course is located inside a course document. Field `courses` was deprecated (now removed).
I've changed my mind about the data architecture since then.

**Comment by ivan-kleshnin** [comment]
Done
