### ISSUE TITLE
Check site

### ISSUE THREAD

**Issue by ivan-kleshnin** [Paqmind/paqmind#27]
Requires full check. Also check `/pages/htmltest/`

**Comment by scabbiaza** [comment]
Horizontal scroll is missing
![screen shot 2016-07-07 at 16 56 13](https://cloud.githubusercontent.com/assets/2734464/16655601/c385581a-4463-11e6-8a06-49d980025a1c.png)

**Comment by ivan-kleshnin** [comment]
2. Fixed in b04eb4ee029b2b22f7144003efe5b99071cb4d90

**Comment by ivan-kleshnin** [comment]
11\. Fixed in c47e878

**Comment by ivan-kleshnin** [comment]
```
<div class="col-xs-12 col-sm-4 right">Mentor: <a href="{{ current.mentorURL }}">{{ current.mentor }}</a></div>
```

Margins for *right** are broken again.

**Comment by ivan-kleshnin** [comment]
12. **Content text is still too wide**

**Comment by ivan-kleshnin** [comment]
Everything is fixed.
