### ISSUE TITLE
Paqmind specific 404 styles

### ISSUE THREAD

**Issue by ivan-kleshnin** [Paqmind/paqmind#29]
Error pages work now but require polishing (fonts!).

Use **direct access** in localhost (`http://localhost:8080/errors/404.html`). 
Redirects (`http://localhost:8080/some-missing-page`) obviously won't work by itself.

**Comment by scabbiaza** [comment]
@ivan-kleshnin: pls recheck the current view

**Comment by ivan-kleshnin** [comment]
Perfect!
