### ISSUE TITLE
Horizontal scroll is missing in code blocks

### ISSUE THREAD

**Issue by scabbiaza** [Paqmind/paqmind#30]
![screen shot 2016-07-19 at 09 03 15](https://cloud.githubusercontent.com/assets/2734464/16940058/b1cc4018-4d8f-11e6-83bc-412f22fff824.png)

**Comment by scabbiaza** [comment]
Added horizontal scroll.

Also currently code block contains only 65 visible chars per line, which is very small.
That is why i increased the width of the block (for big screens only)


![screen shot 2016-07-19 at 09 14 02](https://cloud.githubusercontent.com/assets/2734464/16940243/2c5aa760-4d91-11e6-81ee-25ae6c8c4c9a.png)

**Comment by ivan-kleshnin** [comment]
Great job!

**Comment by ivan-kleshnin** [comment]
There was a bug in the big screens for `.output` code. The gray line was shorter than the code itself. I think width corrections you've made should be applied to `pre` rather than `code`.
Fixed that.
