### ISSUE TITLE
Interview post improvements

### ISSUE THREAD

**Issue by scabbiaza** [Paqmind/paqmind#31]
Great job for this post! And great idea!
Let's keep doing it.

I propose to improve some things:
1. Let's add target="_blank" to the external links. Is it easy?
2. Three times in the post i saw "very very". In one case they were very close.
And here you can see "very" 6 times. I think we could change it.
"XStream is very very different to MostJS I think. It was put together very quickly with the idea of creating a library that is very small, and very simple to use with CycleJS applications. I don't think that the internals ended up very clean, and I don't find it very easy to maintain as a consequence of that."
3. Also let's recheck "more and more" entries.

**Comment by ivan-kleshnin** [comment]
Fixed "very" abuse. Good catch!
