### ISSUE TITLE
Multilines header

### ISSUE THREAD

**Issue by scabbiaza** [Paqmind/paqmind#32]

**Comment by scabbiaza** [comment]
Proposed typography

Big margin tops may look unusually, but i have reasons to do it.
Better have a call about it.

![html tests paqmind](https://cloud.githubusercontent.com/assets/2734464/17830972/a48d1052-66e5-11e6-9616-e000b577e9db.png)
![vertical rythm](https://cloud.githubusercontent.com/assets/2734464/17830973/abeb9c74-66e5-11e6-89aa-e91cb847b7b5.png)

**Comment by ivan-kleshnin** [comment]
Multiline headers require fixed line-height (1.5) 
=> 
requires setting margin values in px 
=> 
they shouldn't be allowed.
