### ISSUE TITLE
Issues in Git course

### ISSUE THREAD

**Issue by scabbiaza** [Paqmind/paqmind#35]
1. Update template:
no need for "Mentor" and "Back to courses" blocks
![screen shot 2016-08-20 at 12 53 29](https://cloud.githubusercontent.com/assets/2734464/17830477/34acbff4-66d5-11e6-86ca-29aca609370c.png)

2. Dunno why generator doesn't create pages from the second level of the hierarchy from `Git course` link. Works only when data is directly in the folder.

3. Address TODO (yellow text)

**Comment by ivan-kleshnin** [comment]
2. Bug. By default `glob` does not follow symlinked dirs. Fixed FYI:

```diff
- glob(mask)
+ glob(mask, {follow: true})
```

**Comment by ivan-kleshnin** [comment]
Decided to keep "Back to Courses" only from course intro pages.

**Comment by scabbiaza** [comment]
Alright, pls remove "Back to Courses" from inner course pages

**Comment by ivan-kleshnin** [comment]
To fix this you need to specify

```yml
template: page/default.html
```

in every non-top `page.yml`
