### ISSUE TITLE
Need help with redesign branch

### ISSUE THREAD

**Issue by scabbiaza** [Paqmind/paqmind#9]
- [x]  Review changes (I)
- [ ]  Replace photos with bigger ones. Could you replace photo with "sea" set? I don't like current (( (I)
- [x]  Update content: check headers, etc. (I)
- [x]  Check on mobile (T)
- [x]  Remove templates for errors (T)
- [x]  Check webpack prod config (T + I)
- [x]  Update articles titles sizes on home page (T)
- [x]  Rename theme, from previous theme we have only fonts

Additionally features
- [ ]  Show menu by scroll up
- [ ]  Add page loader indicator

**Comment by scabbiaza** [comment]
After running `npm run dev` i've got these uncommited files:
```
content/index.yml
content/pages/demo-page.yml
 content/posts/demo-post.yml
```

What i should do with them?

**Comment by ivan-kleshnin** [comment]
> got these uncommited files

Already fixed. Code which generates this was moved to `bin/scaffold`.

**Comment by ivan-kleshnin** [comment]
Now webpack hash is not used. I will add support for [long-term-caching](https://medium.com/@okonetchnikov/long-term-caching-of-static-assets-with-webpack-1ecb139adb95#.7f2ud121m).

**Comment by scabbiaza** [comment]
Async loading for CodeMirror was implemented.
I created separated issues from TODO items that were left and closing this issue.
